const c = @cImport({
    @cInclude("doomtype.h");
    @cInclude("doomdef.h");
});


//
// Map level types.
// The following data structures define the persistent format
// used in the lumps of the WAD files.
//

// Lump order in a map WAD: each map needs a couple of lumps
// to provide a complete scene geometry description.
pub const ML_LABEL: c_int = 0;      // A separator, name, ExMx or MAPxx
pub const ML_THINGS: c_int = 1;     // Monsters, items..
pub const ML_LINEDEFS: c_int = 2;   // LineDefs, from editing
pub const ML_SIDEDEFS: c_int = 3;   // SideDefs, from editing
pub const ML_VERTEXES: c_int = 4;   // Vertices, edited and BSP splits generated
pub const ML_SEGS: c_int = 5;       // LineSegs, from LineDefs split by BSP
pub const ML_SSECTORS: c_int = 6;   // SubSectors, list of LineSegs
pub const ML_NODES: c_int = 7;      // BSP nodes
pub const ML_SECTORS: c_int = 8;    // Sectors, from editing
pub const ML_REJECT: c_int = 9;     // LUT, sector-sector visibility	
pub const ML_BLOCKMAP: c_int = 10;  // LUT, motion clipping, walls/grid element


// A single Vertex.
pub const MapVertex = extern struct {
    x: c_short,
    y: c_short,
};


// A SideDef, defining the visual appearance of a wall,
// by setting textures and offsets.
pub const MapSideDef = extern struct {
    textureoffset: c_short,
    rowoffset: c_short,
    toptexture: [8]u8,
    bottomtexture: [8]u8,
    midtexture: [8]u8,
    // Front sector, towards viewer.
    sector: c_short,
};


// A LineDef, as used for editing, and as input
// to the BSP builder.
pub const MapLineDef = extern struct {
    v1: c_short,
    v2: c_short,
    flags: c_short,
    special: c_short,
    tag: c_short,
    // sidenum[1] will be -1 if one sided
    sidenum: [2]c_short,
};


//
// LineDef attributes.
//

// Solid, is an obstacle.
pub const ML_BLOCKING: c_short = 1;

// Blocks monsters only.
pub const ML_BLOCKMONSTERS: c_short = 2;

// Backside will not be present at all
//  if not two sided.
pub const ML_TWOSIDED: c_short = 4;

// If a texture is pegged, the texture will have
// the end exposed to air held constant at the
// top or bottom of the texture (stairs or pulled
// down things) and will move with a height change
// of one of the neighbor sectors.
// Unpegged textures allways have the first row of
// the texture at the top pixel of the line for both
// top and bottom textures (use next to windows).

// upper texture unpegged
pub const ML_DONTPEGTOP: c_short = 8;

// lower texture unpegged
pub const ML_DONTPEGBOTTOM: c_short = 16;

// In AutoMap: don't map as two sided: IT'S A SECRET!
pub const ML_SECRET: c_short = 32;

// Sound rendering: don't let sound cross two of these.
pub const ML_SOUNDBLOCK: c_short = 64;

// Don't draw on the automap at all.
pub const ML_DONTDRAW: c_short = 128;

// Set if already seen, thus drawn in automap.
pub const ML_MAPPED: c_short = 256;




// Sector definition, from editing.
pub const MapSector = extern struct {
    floorheight: c_short,
    ceilingheight: c_short,
    floorpic: [8]u8,
    ceilingpic: [8]u8,
    lightlevel: c_short,
    special: c_short,
    tag: c_short,
};

// SubSector, as generated by BSP.
pub const MapSubSector = extern struct {
    numsegs: c_short,
    // Index of first one, segs are stored sequentially.
    firstseg: c_short,
};


// LineSeg, generated by splitting LineDefs
// using partition lines selected by BSP builder.
pub const MapSeg = extern struct {
    v1: c_short,
    v2: c_short,
    angle: c_short,
    linedef: c_short,
    side: c_short,
    offset: c_short,
};



// BSP node structure.

// Indicate a leaf.
pub const NF_SUBSECTOR: c_int = 0x8000;

pub const MapNode = extern struct {
    // Partition line from (x,y) to x+dx,y+dy)
    x: c_short,
    y: c_short,
    dx: c_short,
    dy: c_short,

    // Bounding box for each child,
    // clip against view frustum.
    bbox: [2][4]c_short,

    // If NF_SUBSECTOR its a subsector,
    // else it's a node of another subtree.
    children: [2]c_ushort,
};




// Thing definition, position, orientation and type,
// plus skill/visibility flags and attributes.
pub const MapThing = extern struct {
    x: c_short,
    y: c_short,
    angle: c_short,
    type: c_short,
    options: c_short,
};
